COMMAND_DATABASE_REPLACE_FLAG = "$d"

# codeql规则路径替换标志
COMMAND_RULE_REPLACE_FLAG = "$r"

COMMAND_OUTPUT_FLAG = "$o"

COMMAND_CREATE_DATABASE_NAME_REPLACE_FLAG = "%d"

COMMAND_CREATE_PROJECT_PATH_REPLACE_FLAG = "%p"

CODEQL_BIN = "codeql"
CODEQL_CLI = "codeql-codeql-cli-latest"

proxy = ''
